### ISSUE TITLE
pages redirecting to login page even if isAuthorized defined

### ISSUE THREAD

**Issue by lithos77** [cakemanager/cakephp-utils#13]
Hello,
in my controllers I've set 
public function isAuthorized($user) {
        $this->Authorizer->action([' MY METHODS'], function ($auth, $controller) use ($user) {
            $auth->allowRole([1,2,3,4]);
        });
        return $this->Authorizer->authorize();
}

but I must include this in AppController or any method is redirecting to the login:

$this->Auth->allow(['index', 'view', 'display', .... 'customMethod']);

What I'm missing?

**Comment by bobmulder** [comment]
Hey @lithos77,

The `AuthorizerComponent` is meant to rule the authorization when an user is logged in. So with this component you can rule the actions where an user is logged in. The `AuthComponent` (with you last piece of code) is used to set what action should be open for non-logged in users, and logged in users... Hope you understand!

Let me know if you get it ;)
