### ISSUE TITLE
How to troubleshoot uploadable behaviour?

### ISSUE THREAD

**Issue by maartendamen** [cakemanager/cakephp-utils#14]
I am trying to use the uploadable behaviour, I have added the plugin to my bootstrap.php file. And defined the behaviour in my table file: 

```
/**
 * Initialize method
 *
 * @param array $config The configuration for the Table.
 * @return void
 */
public function initialize(array $config)
{
    $this->addBehavior('Utils.Uploadable', [
        'photo',
    ]);
```

I also modified my template:

```
<?= $this->Form->create($player, ['type' => 'file']); ?>

echo $this->Form->input('photo', array('label' => 'Foto', 'type'=>'file'));
```

However when I try to upload a file, nothing seems to happen. I have tried adding debug statements here and there, but it seems the behaviour is not used? How can I troubleshoot this?

**Comment by bobmulder** [comment]
Hey maarten,

The main known problem is that your defined upload field (photo) is equal to the column in your database. That isn't possible yet. Don't know why, but I am working on a fix. So try to define your field different from your column

**Comment by maartendamen** [comment]
Thanks! This was indeed the culprit, I have now defined a photo_field and it's working properly.
Thanks a bunch for creating this, it saves you from a lot of hassle with handling file uploads.

**Comment by bobmulder** [comment]
I've heard about this a lot and the issue irritates me too... I will work on a fix ;). The whole plugin (and all other plugins of the CakeManager team) really help me developing smart and fast :)

**Comment by bobmulder** [comment]
@maartendamen I've a great breakthrough! Hopefully I will commit it tomorow!

**Comment by bobmulder** [comment]
@maartendamen I've updated the uploadableBehavior. You should now be able to use:

```
    $this->addBehavior('Utils.Uploadable', [
        'photo',
    ]);
```

With the `photo`  column in your table where the `filePath` should be saved.

**Comment by bobmulder** [comment]
I assume you fixed it ;)

**Comment by el-rainmaker** [comment]
Hello, This behavior is definitely awesome, however I have a problem displaying the saved image using  the html image helper because its the path of the image that is saved. Is there a way I can save just image.jpg in database column rather than  img\users\image.jpg?

**Comment by bobmulder** [comment]
Hello @eros69,

Read this section of the docs to know more about the different fields who are available: http://cakemanager.org/docs/utils/1.0/behaviors/uploadable/#fields.
For you the `url` or the `fileName` fields would be helpful.
In the docs you will find an example about how to integrate them into your model.

Good luck and happy coding ;)

**Comment by el-rainmaker** [comment]
Hello Bob ,
Really appreciated your swift response to my previous issue regarding
cakemanager uploadable behaviour, please how can I upload multiple pictures
at once with this behaviour.

**Comment by bobmulder** [comment]
Hi @eros69,

You can do this by defining multiple fields in your Table like:

```
  $this->addBehavior('Utils.Uploadable', [
        'photo_1',
        'photo_2',
        'photo_3' => [
            // settings
        ],
    ]);
```

**Comment by el-rainmaker** [comment]
Bob,
 Once again , Thank you.

**Comment by bobmulder** [comment]
No problem! Note that GitHub Issues are not for help questions. Feel free to ask everything at gitter:

https://gitter.im/cakemanager/cakephp-utils

https://gitter.im/bobmulder [private]

**Comment by eros69** [comment]
Hi cakemanager/cakephp-,

I'd like to add you to my professional network on LinkedIn.

- Adeyemi

Confirm that you know Adeyemi: https://www.linkedin.com/e/v2?e=0-ijty63u9-r6&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=-bvnkdeq&invitationId=6097363397089783809








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijty63u9-r6&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHQOrisp2fUSAAAAVJ4vxNowNOMNIg468ESyk52bd0Q0VcWzTRnmgtBPZhcM4OBRM-NYxW-myCHJltZnpP55NBm4ZS4k4_qTqfm3SawPeC2UCp4bXUJCm_8fkEeO2X9uPBVZUnJKzlllCWeJT4lDHf-HNjstAn5FJRE5aQFC1AkuwkYXB0jyWAgS-2iP3Jpldok&eid=0-ijty63u9-r6


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijty63u9-r6&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eros69** [comment]
Hi cakemanager/cakephp-,

I'd like to add you to my professional network on LinkedIn.

- Adeyemi

Confirm that you know Adeyemi: https://www.linkedin.com/e/v2?e=0-ijty63wx-p0&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=5ZCBEJW2&invitationId=6097363396947173376








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijty63wx-p0&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHyWnTs_DnPFwAAAVJ4vwvm3m-RENAdWbE3bscjJR1RoO8lTKD8rrxg86ewuHNcBrXqN_9xCMJWOLIqxcUB2Su7CehdJBGs0TkROucf1-lXf8kFlibXrgHcc-KACXlqVnU7Wk3nBXoQOWSS05KA9WoTv18jnaZpk9RsHiLLvbg7QPelqqadxVq_OTNl3u2QBRWx&eid=0-ijty63wx-p0


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijty63wx-p0&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eros69** [comment]
Adeyemi Ladejobi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-5udz5f-ik4hb2ex-td&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=5ZCBEJW2&invitationID=6097363396947173376

View Adeyemi Ladejobi&#39;s profile: https://www.linkedin.com/e/v2?e=-5udz5f-ik4hb2ex-td&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=5ZCBEJW2&invitationID=6097363396947173376





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-5udz5f-ik4hb2ex-td&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-5udz5f-ik4hb2ex-td&loid=AQHslWQonZTT4gAAAVKffn_-xJ35AfFrsYAeKzQSaESNFE3LjwIylK-t5WR-3bjU29IPbppPRGJ118xZZCNqD60lvifmAHNo3f1Cyn50NthI9VKveB506uLcND9iirFUS_w-dQpIIKPmQC2qfhHWsKNpgJhAMcCAOZhurtXovVUF60kqTJqnWFqCl-CREdjbHk6u

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-5udz5f-ik4hb2ex-td&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eros69** [comment]
Adeyemi Ladejobi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-x539e5-ik4hb2ev-rf&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=-bvnkdeq&invitationID=6097363397089783809

View Adeyemi Ladejobi&#39;s profile: https://www.linkedin.com/e/v2?e=-x539e5-ik4hb2ev-rf&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=-bvnkdeq&invitationID=6097363397089783809





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-x539e5-ik4hb2ev-rf&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-x539e5-ik4hb2ev-rf&loid=AQH02le2QB3v9gAAAVKff2X1Q-nl39PwLwN_E5LB47ul32QFldu3PNie5ek2ucqVsVzFEvh528H9n7rqRH72TAe9-MmyGfQsugRWfB22v2t1pAyDD-cGbFc8KjdY67gtcIJ32W1E1-D2-nAPIlwl4rwelPp99uRZRZNEvIalgWF0vXMhF6F491zkoNWbCjJK1VYD

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-x539e5-ik4hb2ev-rf&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eros69** [comment]
Adeyemi Ladejobi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-5udz5f-ikenf8pb-3o&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=5ZCBEJW2&invitationID=6097363396947173376

View Adeyemi Ladejobi&#39;s profile: https://www.linkedin.com/e/v2?e=-5udz5f-ikenf8pb-3o&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=5ZCBEJW2&invitationID=6097363396947173376





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-5udz5f-ikenf8pb-3o&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-5udz5f-ikenf8pb-3o&loid=AQGflJbfxgkG5AAAAVLEZueocPq-8SZEGEvrvq2FJislFeCLtgLTpIRnbAQd1gisxzqbhgsS4xe0TEpjNhtOCcKa-Ao-n_fh8g_f8q1jU3LCVvDSmVN8MyujHseOiMUuThh4hyZ9YgODEQgQcI6Cs3cHHQ3q_HNsvT8SfJkzzivQQ0fv2Mgqz6wmHPnnP1PRZf26

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-5udz5f-ikenf8pb-3o&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eros69** [comment]
Adeyemi Ladejobi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-x539e5-ikenf8m3-gr&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=-bvnkdeq&invitationID=6097363397089783809

View Adeyemi Ladejobi&#39;s profile: https://www.linkedin.com/e/v2?e=-x539e5-ikenf8m3-gr&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=-bvnkdeq&invitationID=6097363397089783809





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-x539e5-ikenf8m3-gr&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-x539e5-ikenf8m3-gr&loid=AQG3mLYaaBpRHgAAAVLEaWnwqSirKz6RJYYqp6Q_xAJzMZugQM4KkRXpHHCsycMD-j9dYvHBOgxmdQDBJ9ViY0X4Y5FBbwl_oOdH_UH-KNZ7NVUzRVhHvKaJVAaalRnssQ0GK_wQqui4io1lxo4q_s3JpIJ5VvYz4iJKdngfr6vF9MkyRExOavDZdsHvvlL0Dm10

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-x539e5-ikenf8m3-gr&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by brunochichava** [comment]
Hi, im getting an error while tryng to add the behavior to my table, there is my code:

> `$this->addBehavior('Utils.Uploadable', [
>             'photo',
>         ]);`

The error is: Missing behavior.

**Comment by bobmulder** [comment]
Hi @brunochichava, it seems this is another issue so please open up a new one. I think you didn't load the plugin via composer as espected. Please confirm that...

**Comment by brunochichava** [comment]
Ok, i will open another issue, thanks.
