### ISSUE TITLE
Not upload multiple files

### ISSUE THREAD

**Issue by adexerivera** [cakemanager/cakephp-utils#22]
Hi,

I trying to add multiple files with different fields, and it's not possible or I don't know how to do.

``` php
$this->addBehavior('Utils.Uploadable', [
            'audio' => [
                'removeFileOnUpdate' => false,
                'path' => '{ROOT}{DS}{WEBROOT}{DS}uploads{DS}{model}{DS}audio{DS}'
            ],
            'video' => [
                'removeFileOnUpdate' => false,
                'path' => '{ROOT}{DS}{WEBROOT}{DS}uploads{DS}{model}{DS}video{DS}',
            ]
]);
```

I think that problem, is because after save first file on line 149, beforeSave is calling again and data for second file it's lost.

Thanks and regards.

**Comment by bobmulder** [comment]
Hi @adexerivera,

Thank you for posting your issue. I will check out your issue as soon as possible. If you have suggestions to solve this, feel free to open up a new PR!

Greetz

Bob

**Comment by dannyuk1982** [comment]
I am also having this problem, after the first file, nothing saves. I have tried to debug but got nowhere - can you please help Bob!

**Comment by bobmulder** [comment]
@dannyuk1982 and @adexerivera, I am going to take a look at it in 20 minutes! Don't worry ;)

**Comment by bobmulder** [comment]
Almost fixed it :)

**Comment by bobmulder** [comment]
I've fixed it. @adexerivera was right about the location of the bug. I will improve the tests later on, to be ensured that this won't happen again. Thanks for reporting and happy coding :)

**Comment by ghost** [comment]
OK - will give it a go, thanks :)

**Comment by adexerivera** [comment]
Thank you Bob

**Comment by ghost** [comment]
That is working fine for me now - thank you!

**Comment by bobmulder** [comment]
Cool :)

**Comment by leoruhland** [comment]
:+1:

**Comment by bobmulder** [comment]
If you guys have more needs for the uploadable behavior, let me know. It should become a strong easy-to-use behavior!
