### ISSUE TITLE
How to delete files once uploaded?

### ISSUE THREAD

**Issue by ghost** [cakemanager/cakephp-utils#23]
Hello - I cannot find anything in the documentation about this.

Say I have a record that holds one or more images, the user uploads an image, so now it is saved.

The user then edits the record and wants to remove the image, not replace with another - just remove it. 

How is this called? Can say an input checkbox be set, which triggers this on save?

**Comment by bobmulder** [comment]
Hi @danyuk1982,

Good point, this isn't featured yet... A solution for your issue should be: creating a method inside the behavior called `removeFile($entity, $columnName)`. What do you think about that?

Bob

**Comment by ghost** [comment]
Er yea, that could work. Ideally if an input could be set, i.e. {fieldname}.remove and when it saves it remove that image? Would that be a fairly quick thing to implement?

**Comment by bobmulder** [comment]
In fact this method is what you need: https://github.com/cakemanager/cakephp-utils/blob/master/src/Model/Behavior/UploadableBehavior.php#L501

I will think about a way to do this...

**Comment by ghost** [comment]
I don't know cake (I'm a front end dev mainly) but something like this? pseudocode-ish

beforeSave( ....) {

   $fields = $this->getFieldList();
   ...
   foreach ($fields as $field) {
      if $_POST[ "{ $field}.remove" ] == 'ON' ) {
         _removeFile( $field );
      }
     ....
   }
   ...
}

**Comment by bobmulder** [comment]
I understand you want to make a checkbox to set to true to remove an upload. However I don't think this is a solution for everyone. 

What I want to do is adding a method to the behavior which makes it easier to remove images on the fly. This will give you the ability to integrate it with your checkbox-stuff. 

Give me a few minutes, I will open up a new branch to give you the method. Later on I will add tests, and merge it into master... Agree?

**Comment by bobmulder** [comment]
@danyuk1982, please check out the following added method: https://github.com/cakemanager/cakephp-utils/blob/85e9c5e75aa883bf7e11fb0759111bebfc20459f/src/Model/Behavior/UploadableBehavior.php#L101-L105

Just call it with: 

```
$this->YourModel->remove($entity, 'filecolumn`);
```

This method will remove the file, and will set the `filecolumn` in your entity to `null`.

Note: To get this, please use the `master-issue23` branch instead of `master`!

**Comment by bobmulder** [comment]
Please let me know if it's fixed ;)

**Comment by ghost** [comment]
OK thanks - I will try this!
