### ISSUE TITLE
Hint: filename in md5

### ISSUE THREAD

**Issue by adeonir** [cakemanager/cakephp-utils#25]
Hey guys, what about saving the filename in md5 format?

**Comment by vaughany** [comment]
What would be the benefit?

**Comment by bobmulder** [comment]
@vaughany is right... Why should you do that? And IF you want it, maybe you can use a setter method in your entity I guess...

**Comment by adeonir** [comment]
I have seen in other behaviors and like to use... on second thought, it really is not that useful.
But it was only a suggestion.

**Comment by bobmulder** [comment]
But why would you want it?
