### ISSUE TITLE
Reset Button  $this->Search->filterForm

### ISSUE THREAD

**Issue by mugnano** [cakemanager/cakephp-utils#26]
Hello , we use $this->Search->filterForm($searchFilters)
for the filters in the search.

How to insert a "reset button " in the form ?

thank you

**Comment by bobmulder** [comment]
Thats a really good point Fabio! I think we should implement that. Can you make a pr? We can do it together, so get in touch via gitter.im/bobmulder.

Bob

**Comment by bobmulder** [comment]
@mugnano I think it's not too hard to realize this. I will take a look at it as soon as possible!

**Comment by bobmulder** [comment]
Hi @mugnano, unfortunately I don't have that much time to work on this. Do you already have a solution to share?

**Comment by mugnano** [comment]
An idea :

in function filterForm 

$html .= $this->Html->link(__('Reset'), ['controller' => $this->request->param('controller'), 'action' => $this->request->param('action')], ['class' => 'btn btn-primary']);

reload the page and clear filter. Not perfect but it should work

**Comment by mugnano** [comment]
news?

**Comment by bobmulder** [comment]
I will check it out asap ;) sorry for the delay ;) if you trust it, feel free to create a PR! (don't forget tests ;))
