### ISSUE TITLE
Missing behavior when trying to add to tbale

### ISSUE THREAD

**Issue by brunochichava** [cakemanager/cakephp-utils#30]
Hi, im getting an error while tryng to add the behavior to my table, there is my code:

`$this->addBehavior('Utils.Uploadable', [ 'photo', ]);`

The error is: Missing behavior.

Thanks in advance.

**Comment by brunochichava** [comment]
In the other post you said that maybe my composer is not loading the files, i dont know, but  have istalled the plugin via composer, but durring the installation, displayed some errors, what is hapening?

**Comment by bobmulder** [comment]
Please drop the errors and approve that `vendor/cakemanager/cakephp-utils/src/Model/Behavior/UploadableBehavior.php` exists...

**Comment by brunochichava** [comment]
`vendor/cakemanager/cakephp-utils/src/Model/Behavior/UploadableBehavior.php` exists, let me check the errors.

**Comment by brunochichava** [comment]
Here is the error that is showed during the composer installation of the plugin:
![snap 2016-03-31 at 13 56 16](https://cloud.githubusercontent.com/assets/3441605/14175012/927f8d7a-f748-11e5-8919-7d6ffcf12ca4.png)

**Comment by brunochichava** [comment]
My cake plugin directory after installation:
![snap 2016-03-31 at 14 01 11](https://cloud.githubusercontent.com/assets/3441605/14175102/205366ee-f749-11e5-95bb-4a75a4d24a7a.png)
