### ISSUE TITLE
Installation failed for cakePHP 3.1.7

### ISSUE THREAD

**Issue by koffisani** [cakemanager/cakephp-utils#31]
I cannot install this plugin for cakephp 3.1.7. I'm getting : 
`[ErrorException]             
  Undefined variable: baseDir`

The complete result is as follows : 

``` bash
[koffi:/opt/lampp/htdocs/project] master(+10165/-608) 2s 127 ± composer require cakemanager/cakephp-utils:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing cakephp/bake (1.1.3)
  - Installing cakephp/bake (1.1.4)
    Loading from cache
Installation failed, reverting ./composer.json to its original content.
  [ErrorException]             
  Undefined variable: baseDir  
require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
[koffi:/opt/lampp/htdocs/project] master(+10165/-608) 4m25s 1 ± 
```

How to fix this ?

**Comment by bobmulder** [comment]
Hey @koffisani,

Thank you for noticing! I can't reproduce this error at the moment... I'll try it as soon as possible. 

Else, feel free to open a PR to fix this ;)

Greetz,

Bob

**Comment by bobmulder** [comment]
Hi @koffisani,

Probably this has something to do with your issue?

https://github.com/cakephp/plugin-installer/pull/32

https://github.com/cakephp/plugin-installer/issues/30

Please post some updates about the state!

**Comment by koffisani** [comment]
I just change LAMPP version, and reinstall cake, and everything goes well. Thanks for helping.
