### ISSUE TITLE
Uploadable Validation

### ISSUE THREAD

**Issue by doonot** [cakemanager/cakephp-utils#36]
We would like to validate the uploaded files for their file extension. E.g. it should only be possible to upload images (PNG, GIF, JPG, BMP). On the docs it says this is on your roadmap. Do you plan to release anything soon?

Thanks!

**Comment by bobmulder** [comment]
Hi @doonot, I guess I just replied your e-mail, right?

Bob

**Comment by qqqqb** [comment]
Hi @doonot 

You can use cakephp validation to avoid uploading non-image file
`$validator->add('avatar', 'file', ['rule' => ['mimeType', ['image/jpeg', 'image/png']]]);`

And here list of mime types of all files
https://www.sitepoint.com/web-foundations/mime-types-complete-list/
