### ISSUE TITLE
Requet for Necessay Document 

### ISSUE THREAD

**Issue by tarikul05** [cakemanager/cakephp-utils#37]
Hello sir,
I am using the you awesome plugins but from some days i didn't find you documentation in you domain http://cakemanager.org/docs/utils/1.0/ may be domain validity is expired 
will you please share you document link

**Comment by leoruhland** [comment]
Hey @tarikul05, the docs is here: https://github.com/cakemanager/utils-docs

**Comment by qqqqb** [comment]
All documents are available now at [Wiki](https://github.com/cakemanager/cakephp-utils/wiki)
